config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 root to: "massages#index"
 
 resources :massages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/massage.rb
class Massage < ApplicationRecord
    validates :content, presence: true, length: { maximum: 255 }
    validates :title, presence: true, length: {maximum: 255}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/massages_controller.rb
class MassagesController < ApplicationController
    before_action :set_massage, only: [:show, :edit, :update, :destroy]
    
    
    def index
        @massages  = Massage.order(id: :desc).page(params[:page]).per(3)
    end
    
    def show
    end
    
    def new
        @massage = Massage.new
    end
    
    def create
        @massage = Massage.new(massage_params)
        
        if @massage.save
            flash[:success] = "Massage が正常に投稿されました"
            redirect_to @massage
        else
            flash.now[:danger] = "Massage が投稿されませんでした"
            render :new
        end
    end
    
    def edit
    end
    
    def update
        if 
            @massage.upgrade(massage_params)
            flash[:success] = "Massage は正常に更新されました"
            redirect_to @massage
        else
            flash.new[:danger] = "Massage は更新されませんでした"
            render :edit
        end
    end
    
    def destroy
        set_massage
        @massage.destroy
        
        flash[:success] = "Massage は正常に削除されました"
        redirect_to massages_url
    end
    
    private
    
    def set_massage
        @massage = Massage.find(params[:id])
    end
        
    # Strong Parameter
    def massage_params
        params.require(:massage).permit(:content, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_massages.html.erb
<% flash.each do |massage_type, massage| %>
    <div class="alert alert-<%= massage_type %>"><%= massage %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">MessageBoard</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- メニュー項目 -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to  '新規メッセージの投稿', new_massage_path, class: 'nav-link' %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MassageBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render "layouts/flash_massages" %>
  
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </body>
</html>

app/views/massages/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: message, local: true) do |f| %>
      <% if message.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% message.errors.full_massages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="form-group">
        <%= f.label :title, 'タイトル' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :content, 'メッセージ' %>
        <%= f.text_field :content, class: 'form-control' %>
      </div>

      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/massages/edit.html.erb
<h1>id: <%= @massage.id %> のメッセージ編集ページ</h1>

<%= render 'form', message: @massage %>

app/views/massages/index.html.erb
<h1>メッセージ一覧</h1>

<% if @massages.any? %>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>id</th>
                <th>タイトル</th>
                <th>メッセージ</th>
            </tr>
        </thead>
        <tbody>
            <% @massages.each do |massage| %>
                <tr>
                    <td><%= link_to massage.id, massage %></td>
                    <td><%= massage.title %></td>
                    <td><%= massage.content %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <div>
        <%= paginate @massages %>
    </div>
<% end %>

<%= link_to '新規メッセージの投稿', new_massage_path, class: "btn btn-primary" %>

app/views/massages/new.html.erb
<h1>メッセージ新規作成ページ</h1>

<%= render "form", massage: @massage %>

app/views/massages/show.html.erb
<h1>id: <%= @massage.id %> のメッセージ詳細ページ</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @massage.id %></td>
  </tr>
  <tr>
    <th>タイトル</th>
    <td><%= @massage.title %></td>
  </tr>
  <tr>
    <th>メッセージ</th>
    <td><%= @massage.content %></td>
  </tr>
</table>


<%= link_to 'このメッセージを編集する', edit_massage_path(@massage), class: 'btn btn-light' %>
<%= link_to "このメッセージを削除する", @massage, method: :delete, data: { confirm: "本当に削除してよろしいでしょうか？"}, class: "btn btn-danger"  %> 